# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm run install-client
    npm run test-client
  displayName: 'Run Tests - wc-guest-management.client'
  timeoutInMinutes: 5

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './test-report.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/wc-guest-management.client'
    failTaskOnFailedTests: true
  displayName: 'Publish Test Results - wc-guest-management.client'
