# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  displayName: 'Install Node.js'
  inputs:
    versionSpec: '12.x'

- task: Npm@1
  displayName: 'wc-guest-management install [client]'
  inputs:
    command: 'custom'
    customCommand: 'run install-client'

- task: Npm@1
  displayName: 'wc-guest-management tests [client]'
  inputs:
    command: 'custom'
    customCommand: 'run test-client'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: './wc-guest-management.client/**/test-*.xml'
    failTaskOnFailedTests: true
